#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "little_ghost/cli"

source_path = File.expand_path("..", __dir__)
source_path = nil unless File.file?(File.join(source_path, "little_ghost.gemspec"))

exit LittleGhost::CLI.new(ARGV, source_path:).run
